spring.application.name=platanitos
spring.datasource.url=jdbc:mysql//localhost:3306/platanitos
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret = CLAVESECRETASECRETITAINDETECTABLEYDESAPERCIBIDAUNFRONTDENTRODEOTRO2026
jwt.expiration = 86400000